$lines = @(
"package com.example.ocrreader.tts",
"",
"import android.content.Context",
"import android.content.Intent",
"import android.content.pm.ResolveInfo",
"import android.media.AudioAttributes",
"import android.speech.tts.TextToSpeech",
"import android.speech.tts.UtteranceProgressListener",
"import android.util.Log",
"import java.util.Locale",
"",
"class TtsManager(private val context: Context) : TextToSpeech.OnInitListener {",
"",
"    private var tts: TextToSpeech? = null",
"    private var isInitialized = false",
"    private var speechRate = 1.0f",
"    private var engineName: String = \"\"",
"    private var initStatus: Int = -2",
"",
"    private var knownEngines = listOf(",
"        \"\",",
"        \"com.android.tts\",",
"        \"com.google.android.tts\",",
"        \"com.samsung.SMT\",",
"        \"com.xiaomi.mibrain.speech\",",
"        \"com.xiaomi.mibrain.speech.tts\",",
"        \"com.iflytek.speechsuite\",",
"        \"com.baidu.duer.tts\",",
"        \"com.huawei.hmos.tts\",",
"        \"com.huawei.android.tts\",",
"        \"com.meizu.flyme.speech\",",
"        \"com.oppo.tts\",",
"        \"com.vivo.tts\",",
"        \"com.android.accessibility.tts\",",
"        \"com.svox.pico\",",
"        \"com.android.honeycomb.voiceservice\"",
"    )",
"",
"    private var availableEngines: List<String> = emptyList()",
"    private var currentEngineIndex: Int = 0",
"",
"    private var onTtsReady: (() -> Unit)? = null",
"    private var onSpeechCompleted: (() -> Unit)? = null",
"    private var onCharacterProgress: ((Int) -> Unit)? = null",
"",
"    init {",
"        discoverEngines()",
"        tryInitTts()",
"    }",
"",
"    private fun discoverEngines() {",
"        try {",
"            val intent = Intent(TextToSpeech.Engine.ACTION_CHECK_TTS_DATA)",
"            val services = context.packageManager.queryIntentServices(intent, 0)",
"            Log.d(\"TTS\", \"Found \" + services.size + \" available TTS engines:\")",
"            services.forEach { info ->",
"                Log.d(\"TTS\", \"  - \" + info.serviceInfo.packageName + \" (label: \" + info.loadLabel(context.packageManager) + \")\")",
"            }",
"            availableEngines = services.map { it.serviceInfo.packageName }",
"        } catch (e: Exception) {",
"            Log.e(\"TTS\", \"Failed to discover engines: \" + e.message)",
"            availableEngines = emptyList()",
"        }",
"    }",
"",
"    private fun getEngineList(): List<String> {",
"        val combined = mutableListOf<String>()",
"        combined.addAll(knownEngines)",
"        availableEngines.forEach { engine ->",
"            if (!combined.contains(engine)) {",
"                combined.add(engine)",
"            }",
"        }",
"        Log.d(\"TTS\", \"Total engines to try: \" + combined.size)",
"        return combined",
"    }",
"",
"    private fun tryInitTts() {",
"        Log.d(\"TTS\", \"Starting TTS initialization\")",
"        currentEngineIndex = 0",
"        tryNextEngine()",
"    }",
"",
"    private fun tryNextEngine() {",
"        val engines = getEngineList()",
"        if (currentEngineIndex >= engines.size) {",
"            Log.e(\"TTS\", \"All engines failed\")",
"            initStatus = -1",
"            return",
"        }",
"",
"        val engineName = engines[currentEngineIndex]",
"        Log.d(\"TTS\", \"Trying engine \" + currentEngineIndex + \": \" + (if (engineName.isEmpty()) \"default\" else engineName))",
"",
"        if (tts != null) {",
"            tts?.shutdown()",
"            tts = null",
"        }",
"",
"        if (engineName.isEmpty()) {",
"            tts = TextToSpeech(context, this)",
"        } else {",
"            tts = TextToSpeech(context, this, engineName)",
"        }",
"    }",
"",
"    fun retryInit() {",
"        if (tts != null) {",
"            tts?.shutdown()",
"            tts = null",
"        }",
"        isInitialized = false",
"        initStatus = -2",
"        currentEngineIndex = 0",
"        discoverEngines()",
"        tryInitTts()",
"    }",
"",
"    override fun onInit(status: Int) {",
"        initStatus = status",
"        Log.d(\"TTS\", \"onInit called with status: \" + status)",
"",
"        if (status == TextToSpeech.SUCCESS) {",
"            this.engineName = tts?.defaultEngine ?: \"Unknown\"",
"            Log.d(\"TTS\", \"Engine name: \" + this.engineName)",
"",
"            val chineseLocales = listOf(",
"                Locale.SIMPLIFIED_CHINESE,",
"                Locale.CHINA,",
"                Locale.CHINESE,",
"                Locale(\"zh\", \"CN\"),",
"                Locale(\"zh\", \"HK\"),",
"                Locale(\"zh\", \"TW\"),",
"                Locale(\"zh_CN\")",
"            )",
"",
"            var localeSet = false",
"            for (locale in chineseLocales) {",
"                val result = tts?.setLanguage(locale)",
"                Log.d(\"TTS\", \"Trying locale: \" + locale + \", result: \" + result)",
"",
"                if (result != TextToSpeech.LANG_MISSING_DATA &&",
"                    result != TextToSpeech.LANG_NOT_SUPPORTED) {",
"                    localeSet = true",
"                    Log.d(\"TTS\", \"Locale set successfully: \" + locale)",
"                    break",
"                }",
"            }",
"",
"            if (!localeSet) {",
"                tts?.setLanguage(Locale.getDefault())",
"                Log.w(\"TTS\", \"Using default locale\")",
"            }",
"",
"            val audioAttributes = AudioAttributes.Builder()",
"                .setUsage(AudioAttributes.USAGE_MEDIA)",
"                .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)",
"                .build()",
"            tts?.setAudioAttributes(audioAttributes)",
"",
"            isInitialized = true",
"            tts?.setOnUtteranceProgressListener(object : UtteranceProgressListener() {",
"                override fun onStart(utteranceId: String?) {}",
"                override fun onDone(utteranceId: String?) {",
"                    onSpeechCompleted?.invoke()",
"                    onCharacterProgress?.invoke(-1)",
"                }",
"                override fun onError(utteranceId: String?) {",
"                    onSpeechCompleted?.invoke()",
"                    onCharacterProgress?.invoke(-1)",
"                }",
"                override fun onRangeStart(utteranceId: String?, start: Int, end: Int, frame: Int) {",
"                    onCharacterProgress?.invoke(end)",
"                }",
"            })",
"",
"            onTtsReady?.invoke()",
"",
"            testSpeak()",
"        } else {",
"            Log.e(\"TTS\", \"Initialization failed with status: \" + status + \", trying next engine\")",
"",
"            currentEngineIndex++",
"            tryNextEngine()",
"        }",
"    }",
"",
"    private fun testSpeak() {",
"        val testResult = tts?.speak(\"语音引擎已就绪\", TextToSpeech.QUEUE_FLUSH, null)",
"        Log.d(\"TTS\", \"Test speak result: \" + testResult)",
"    }",
"",
"    fun setOnTtsReadyListener(listener: () -> Unit) {",
"        if (isInitialized) {",
"            listener.invoke()",
"        } else {",
"            onTtsReady = listener",
"        }",
"    }",
"",
"    fun setOnSpeechCompletedListener(listener: () -> Unit) {",
"        onSpeechCompleted = listener",
"    }",
"",
"    fun setOnCharacterProgressListener(listener: (Int) -> Unit) {",
"        onCharacterProgress = listener",
"    }",
"",
"    fun getEngineName(): String {",
"        return engineName",
"    }",
"",
"    fun isInitialized(): Boolean {",
"        return isInitialized",
"    }",
"",
"    fun getInitStatus(): Int {",
"        return initStatus",
"    }",
"",
"    fun speak(text: String) {",
"        if (!isInitialized || tts == null) {",
"            Log.e(\"TTS\", \"TTS not initialized\")",
"            return",
"        }",
"",
"        if (text.isEmpty()) {",
"            Log.e(\"TTS\", \"Empty text\")",
"            return",
"        }",
"",
"        tts?.stop()",
"",
"        val params = HashMap<String, String>()",
"        params[TextToSpeech.Engine.KEY_PARAM_UTTERANCE_ID] = \"utterance_\" + System.currentTimeMillis()",
"",
"        val result = tts?.speak(text, TextToSpeech.QUEUE_FLUSH, params)",
"        Log.d(\"TTS\", \"Speak result: \" + result + \", text length: \" + text.length)",
"    }",
"",
"    fun pause() {",
"        tts?.stop()",
"    }",
"",
"    fun stop() {",
"        tts?.stop()",
"        onCharacterProgress?.invoke(-1)",
"    }",
"",
"    fun setSpeechRate(rate: Float) {",
"        speechRate = rate",
"        tts?.setSpeechRate(rate)",
"    }",
"",
"    fun getSpeechRate(): Float {",
"        return speechRate",
"    }",
"",
"    fun isSpeaking(): Boolean {",
"        return tts?.isSpeaking ?: false",
"    }",
"",
"    fun release() {",
"        tts?.stop()",
"        tts?.shutdown()",
"        tts = null",
"    }",
"}"
)

$lines | Set-Content -Path "E:\test\test1\app\src\main\java\com\example\ocrreader\tts\TtsManager.kt" -Encoding UTF8
Write-Host "TtsManager.kt updated successfully"